CATEGORY_TO_ICON = {
    "Bakeries": "food",
    "Barbeque": "food",
    "Bars": "drink",
    "Beer Bar": "drink",
    "Beer, Wine & Spirits": "drink",
    "Breakfast & Brunch": "food",
    "Cafes": "food",
    "Cajun/Creole": "food",
    "Cocktail Bars": "drink",
    "Delis": "food",
    "Dive Bars": "drink",
    "French": "food",
    "Gelato": "food",
    "Grocery": "grocery",
    "Hotels": "lodging",
    "Irish Pub": "drink",
    "Local Flavor": "culture",
    "Mediterranean": "food",
    "Music Venues": "culture",
    "New American": "food",
    "Parks": "park",
    "Piano Bars": "drink",
    "Pizza": "food",
    "Seafood": "food",
    "Social Clubs": "culture",
    "Southern": "food",
    "Steakhouses": "food",
    "Wine Bars": "drink",
}
